import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <Link href="/contact">
            <a className={styles.card}>
              <h2>Next subpage</h2>
              <p>Click</p>
            </a>
          </Link>

          <a href="../index.html" className={styles.card}>
            <h2>Main Cordova Index &rarr;</h2>
            <p>Click</p>
          </a>

          <a href="../react-app/index.html" className={styles.card}>
            <h2>Our React app</h2>
            <p>Click</p>
          </a>
        </div>
      </main>
    </div>
  )
}
