import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { Link as RouterLink,
  BrowserRouter as Router, } from "react-router-dom";
import { Fragment } from 'react';
import {
    Route,
} from "react-router-dom";
import Contact from './contact';

const DynamicComponentWithNoSSR = dynamic(
  () => import('./cordovacomponent'),
  { ssr: false })

export default function Home() {
  
  const Wrapper = global.window ? Router : Fragment;
  return (
    <Wrapper>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <div className={styles.grid}>
            <Link href="/contact">
              <a className={styles.card}>
                <h2>Next subpage</h2>
                <p>Click</p>
              </a>
            </Link>
            <RouterLink to="/ciekawe">
              <a className={styles.card}>
                <h2>Next by used with react-router</h2>
                <p>Click</p>
              </a>
            </RouterLink>

            <a href="../index.html" className={styles.card}>
              <h2>Main Cordova Index &rarr;</h2>
              <p>Click</p>
            </a>

            <a href="../react-app/index.html" className={styles.card}>
              <h2>Our React app</h2>
              <p>Click</p>
            </a>
          </div>
        </main>
      </div>
    </Wrapper>
  )
}
